name: airport-checkin

on:
  # push
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '10 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: run codes
      run: python main1.py
